env:
  browser: true
  node: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - warn
    - unix
  quotes:
    - warn
    - double
  semi:
    - error
    - always
  no-console:
    - off
